////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_MET_ZONE_MESG_HPP)
#define FIT_MET_ZONE_MESG_HPP

#include "fit_mesg.hpp"

namespace fit
{

class MetZoneMesg : public Mesg
{
   public:
      MetZoneMesg(void) : Mesg(Profile::MESG_MET_ZONE)
      {
      }

      MetZoneMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns message_index field
      ///////////////////////////////////////////////////////////////////////
      FIT_MESSAGE_INDEX GetMessageIndex(void)
      {
         return GetFieldUINT16Value(254);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set message_index field
      ///////////////////////////////////////////////////////////////////////
      void SetMessageIndex(FIT_MESSAGE_INDEX messageIndex)
      {
         SetFieldUINT16Value(254, messageIndex);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns high_bpm field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetHighBpm(void)
      {
         return GetFieldUINT8Value(1);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set high_bpm field
      ///////////////////////////////////////////////////////////////////////
      void SetHighBpm(FIT_UINT8 highBpm)
      {
         SetFieldUINT8Value(1, highBpm);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns calories field
      // Units: kcal / min
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetCalories(void)
      {
         return GetFieldFLOAT32Value(2);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set calories field
      // Units: kcal / min
      ///////////////////////////////////////////////////////////////////////
      void SetCalories(FIT_FLOAT32 calories)
      {
         SetFieldFLOAT32Value(2, calories);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns fat_calories field
      // Units: kcal / min
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetFatCalories(void)
      {
         return GetFieldFLOAT32Value(3);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set fat_calories field
      // Units: kcal / min
      ///////////////////////////////////////////////////////////////////////
      void SetFatCalories(FIT_FLOAT32 fatCalories)
      {
         SetFieldFLOAT32Value(3, fatCalories);
      }

};

} // namespace fit

#endif // !defined(FIT_MET_ZONE_MESG_HPP)
