////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_ZONES_TARGET_MESG_HPP)
#define FIT_ZONES_TARGET_MESG_HPP

#include "fit_mesg.hpp"

namespace fit
{

class ZonesTargetMesg : public Mesg
{
   public:
      ZonesTargetMesg(void) : Mesg(Profile::MESG_ZONES_TARGET)
      {
      }

      ZonesTargetMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns max_heart_rate field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetMaxHeartRate(void)
      {
         return GetFieldUINT8Value(1);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set max_heart_rate field
      ///////////////////////////////////////////////////////////////////////
      void SetMaxHeartRate(FIT_UINT8 maxHeartRate)
      {
         SetFieldUINT8Value(1, maxHeartRate);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns threshold_heart_rate field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetThresholdHeartRate(void)
      {
         return GetFieldUINT8Value(2);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set threshold_heart_rate field
      ///////////////////////////////////////////////////////////////////////
      void SetThresholdHeartRate(FIT_UINT8 thresholdHeartRate)
      {
         SetFieldUINT8Value(2, thresholdHeartRate);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns functional_threshold_power field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetFunctionalThresholdPower(void)
      {
         return GetFieldUINT16Value(3);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set functional_threshold_power field
      ///////////////////////////////////////////////////////////////////////
      void SetFunctionalThresholdPower(FIT_UINT16 functionalThresholdPower)
      {
         SetFieldUINT16Value(3, functionalThresholdPower);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns hr_calc_type field
      ///////////////////////////////////////////////////////////////////////
      FIT_HR_ZONE_CALC GetHrCalcType(void)
      {
         return GetFieldENUMValue(5);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set hr_calc_type field
      ///////////////////////////////////////////////////////////////////////
      void SetHrCalcType(FIT_HR_ZONE_CALC hrCalcType)
      {
         SetFieldENUMValue(5, hrCalcType);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns pwr_calc_type field
      ///////////////////////////////////////////////////////////////////////
      FIT_PWR_ZONE_CALC GetPwrCalcType(void)
      {
         return GetFieldENUMValue(7);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set pwr_calc_type field
      ///////////////////////////////////////////////////////////////////////
      void SetPwrCalcType(FIT_PWR_ZONE_CALC pwrCalcType)
      {
         SetFieldENUMValue(7, pwrCalcType);
      }

};

} // namespace fit

#endif // !defined(FIT_ZONES_TARGET_MESG_HPP)
