////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_FIELD_CAPABILITIES_MESG_HPP)
#define FIT_FIELD_CAPABILITIES_MESG_HPP

#include "fit_mesg.hpp"

namespace fit
{

class FieldCapabilitiesMesg : public Mesg
{
   public:
      FieldCapabilitiesMesg(void) : Mesg(Profile::MESG_FIELD_CAPABILITIES)
      {
      }

      FieldCapabilitiesMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns message_index field
      ///////////////////////////////////////////////////////////////////////
      FIT_MESSAGE_INDEX GetMessageIndex(void)
      {
         return GetFieldUINT16Value(254);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set message_index field
      ///////////////////////////////////////////////////////////////////////
      void SetMessageIndex(FIT_MESSAGE_INDEX messageIndex)
      {
         SetFieldUINT16Value(254, messageIndex);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns file field
      ///////////////////////////////////////////////////////////////////////
      FIT_FILE GetFile(void)
      {
         return GetFieldENUMValue(0);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set file field
      ///////////////////////////////////////////////////////////////////////
      void SetFile(FIT_FILE file)
      {
         SetFieldENUMValue(0, file);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns mesg_num field
      ///////////////////////////////////////////////////////////////////////
      FIT_MESG_NUM GetMesgNum(void)
      {
         return GetFieldUINT16Value(1);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set mesg_num field
      ///////////////////////////////////////////////////////////////////////
      void SetMesgNum(FIT_MESG_NUM mesgNum)
      {
         SetFieldUINT16Value(1, mesgNum);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns field_num field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetFieldNum(void)
      {
         return GetFieldUINT8Value(2);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set field_num field
      ///////////////////////////////////////////////////////////////////////
      void SetFieldNum(FIT_UINT8 fieldNum)
      {
         SetFieldUINT8Value(2, fieldNum);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns count field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetCount(void)
      {
         return GetFieldUINT16Value(3);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set count field
      ///////////////////////////////////////////////////////////////////////
      void SetCount(FIT_UINT16 count)
      {
         SetFieldUINT16Value(3, count);
      }

};

} // namespace fit

#endif // !defined(FIT_FIELD_CAPABILITIES_MESG_HPP)
