////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_SOFTWARE_MESG_HPP)
#define FIT_SOFTWARE_MESG_HPP

#include "fit_mesg.hpp"

namespace fit
{

class SoftwareMesg : public Mesg
{
   public:
      SoftwareMesg(void) : Mesg(Profile::MESG_SOFTWARE)
      {
      }

      SoftwareMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns message_index field
      ///////////////////////////////////////////////////////////////////////
      FIT_MESSAGE_INDEX GetMessageIndex(void)
      {
         return GetFieldUINT16Value(254);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set message_index field
      ///////////////////////////////////////////////////////////////////////
      void SetMessageIndex(FIT_MESSAGE_INDEX messageIndex)
      {
         SetFieldUINT16Value(254, messageIndex);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns version field
      ///////////////////////////////////////////////////////////////////////
      FIT_FLOAT32 GetVersion(void)
      {
         return GetFieldFLOAT32Value(3);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set version field
      ///////////////////////////////////////////////////////////////////////
      void SetVersion(FIT_FLOAT32 version)
      {
         SetFieldFLOAT32Value(3, version);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns part_number field
      ///////////////////////////////////////////////////////////////////////
      string GetPartNumber(void)
      {
         return GetFieldSTRINGValue(5);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set part_number field
      ///////////////////////////////////////////////////////////////////////
      void SetPartNumber(string partNumber)
      {
         SetFieldSTRINGValue(5, partNumber);
      }

};

} // namespace fit

#endif // !defined(FIT_SOFTWARE_MESG_HPP)
