////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_FILE_ID_MESG_HPP)
#define FIT_FILE_ID_MESG_HPP

#include "fit_mesg.hpp"

namespace fit
{

class FileIdMesg : public Mesg
{
   public:
      FileIdMesg(void) : Mesg(Profile::MESG_FILE_ID)
      {
      }

      FileIdMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns type field
      ///////////////////////////////////////////////////////////////////////
      FIT_FILE GetType(void)
      {
         return GetFieldENUMValue(0);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set type field
      ///////////////////////////////////////////////////////////////////////
      void SetType(FIT_FILE type)
      {
         SetFieldENUMValue(0, type);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns manufacturer field
      ///////////////////////////////////////////////////////////////////////
      FIT_MANUFACTURER GetManufacturer(void)
      {
         return GetFieldUINT16Value(1);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set manufacturer field
      ///////////////////////////////////////////////////////////////////////
      void SetManufacturer(FIT_MANUFACTURER manufacturer)
      {
         SetFieldUINT16Value(1, manufacturer);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns product field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetProduct(void)
      {
         return GetFieldUINT16Value(2);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set product field
      ///////////////////////////////////////////////////////////////////////
      void SetProduct(FIT_UINT16 product)
      {
         SetFieldUINT16Value(2, product);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns serial_number field
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT32Z GetSerialNumber(void)
      {
         return GetFieldUINT32ZValue(3);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set serial_number field
      ///////////////////////////////////////////////////////////////////////
      void SetSerialNumber(FIT_UINT32Z serialNumber)
      {
         SetFieldUINT32ZValue(3, serialNumber);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns time_created field
      // Comment: Only set for files that are can be created/erased.
      ///////////////////////////////////////////////////////////////////////
      FIT_DATE_TIME GetTimeCreated(void)
      {
         return GetFieldUINT32Value(4);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set time_created field
      // Comment: Only set for files that are can be created/erased.
      ///////////////////////////////////////////////////////////////////////
      void SetTimeCreated(FIT_DATE_TIME timeCreated)
      {
         SetFieldUINT32Value(4, timeCreated);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number field
      // Comment: Only set for files that are not created/erased.
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT16 GetNumber(void)
      {
         return GetFieldUINT16Value(5);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set number field
      // Comment: Only set for files that are not created/erased.
      ///////////////////////////////////////////////////////////////////////
      void SetNumber(FIT_UINT16 number)
      {
         SetFieldUINT16Value(5, number);
      }

};

} // namespace fit

#endif // !defined(FIT_FILE_ID_MESG_HPP)
