////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_MESG_DEFINITION_HPP)
#define FIT_MESG_DEFINITION_HPP

#include <ostream>
using namespace std;

#include "fit.hpp"
#include "fit_field_definition.hpp"
#include "fit_mesg.hpp"

namespace fit
{

class MesgDefinition
{
   public:
      MesgDefinition();
      MesgDefinition(Mesg& mesg);
      FIT_BOOL operator==(const MesgDefinition& mesg);
      FIT_BOOL operator!=(const MesgDefinition& mesg);
      int Write(ostream &file);

   private:
      FIT_UINT16 num;
      vector<FieldDefinition> fields;
};

} // namespace fit

#endif // defined(FIT_MESG_DEFINITION_HPP)
