////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_MESG_WITH_EVENT_HPP)
#define FIT_MESG_WITH_EVENT_HPP

#include "fit.hpp"
#include "fit_profile.hpp"

namespace fit
{

class MesgWithEvent
{
   public:
      virtual FIT_DATE_TIME GetTimestamp(void) = 0;
      virtual void SetTimestamp(FIT_DATE_TIME timestamp) = 0;
      virtual FIT_EVENT GetEvent() = 0;
      virtual void SetEvent(FIT_EVENT event) = 0;
      virtual FIT_EVENT_TYPE GetEventType() = 0;
      virtual void SetEventType(FIT_EVENT_TYPE type) = 0;
      virtual FIT_UINT8 GetEventGroup() = 0;
      virtual void SetEventGroup(FIT_UINT8 group) = 0;
};

} // namespace fit

#endif // !defined(FIT_MESG_WITH_EVENT_HPP)
