////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_FIELD_CAPABILITIES_MESG_LISTENER_HPP)
#define FIT_FIELD_CAPABILITIES_MESG_LISTENER_HPP

#include "fit_field_capabilities_mesg.hpp"

namespace fit
{

class FieldCapabilitiesMesgListener
{
   public:
      virtual void OnMesg(FieldCapabilitiesMesg& mesg) = 0;
};

} // namespace fit

#endif // !defined(FIT_FIELD_CAPABILITIES_MESG_LISTENER_HPP)
