////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_FIELD_DEFINITION_HPP)
#define FIT_FIELD_DEFINITION_HPP

#include <ostream>
using namespace std;

#include "fit.hpp"
#include "fit_field.hpp"

namespace fit
{

class FieldDefinition
{
   public:
      FieldDefinition(const Field& field);
      FieldDefinition(const Field* field);
      FIT_BOOL operator==(const FieldDefinition& field);
      FIT_BOOL operator!=(const FieldDefinition& field);
      FIT_UINT8 Write(ostream &file);

   private:
      FIT_UINT8 num;
      FIT_UINT8 size;
      FIT_UINT8 type;
};

} // namespace fit

#endif // defined(FIT_FIELD_DEFINITION_HPP)
