////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_ENCODE_HPP)
#define FIT_ENCODE_HPP

#include <iostream>

#include "fit.hpp"
#include "fit_mesg_listener.hpp"
#include "fit_mesg_definition.hpp"

using namespace std;

namespace fit
{

class Encode : public MesgListener
{
   public:
      Encode(void);
      void Open(iostream& file);
      void Write(Mesg& mesg);
      FIT_BOOL Close(void);
      void OnMesg(Mesg& mesg);

   private:
      void WriteFileHeader(void);

      MesgDefinition lastMesgDefinition;
      long dataSize;
      iostream *file;
};

} // namespace fit

#endif // defined(FIT_ENCODE_HPP)
